<?php

namespace Ais\RuangBundle\Repository;

/**
 * RuangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuangRepository extends \Doctrine\ORM\EntityRepository
{
}
